[project]
name = "cascaded-rls"
version = "0.1.0"
description = "Toolbox for cascaded RLS implementations"
readme = "README.md"
authors = [
    { name = "Basil Liekens", email = "basil.liekens@esat.kuleuven.be" }
]
requires-python = ">=3.14"
dependencies = [
    "jax>=0.11.1",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pyyaml>=6.0.3",
]

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "SIM", "I"]
ignore = []

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
