# Purpose of script:
# Run a simulation of GEIC using both an integrated and cascaded approach to
# validate the following:
# - Equivalence between outputs generated by both
# - The physical interpretability of the cascaded approach
#
# Context:
# Experiments to confirm whether cascaded RLS is indeed a possible replacement
# for regular RLS.
#
# (c) Basil Liekens - ESAT/STADIUS - KU Leuven

import os
import sys

import jax
import jax.numpy as jnp
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

from cascaded_rls import applications, signal_generation


@jax.jit
def run_integrated_geic(
    p: applications.geic_params,
    m_d: jax.Array,
    m_n: jax.Array,
    m_e: jax.Array,
    e: jax.Array,
) -> tuple[applications.geic_params, jax.Array, jax.Array, jax.Array]:
    def _inner_loop(
        p_k: applications.geic_params,
        x_k: tuple[jax.Array, jax.Array, jax.Array, jax.Array],
    ) -> tuple[applications.geic_params, tuple[jax.Array, jax.Array, jax.Array]]:
        p_new, err_d_k, err_n_k, err_e_k = applications.step_geic(p_k, *x_k)
        return p_new, (err_d_k, err_n_k, err_e_k)

    p_final, errs = jax.lax.scan(_inner_loop, init=p, xs=(m_d, m_n, m_e, e))
    return p_final, *errs


@jax.jit
def run_cascaded_geic(
    p: applications.geic_params,
    m_d: jax.Array,
    m_n: jax.Array,
    m_e: jax.Array,
    e: jax.Array,
    w_sc_exp: jax.Array,
    w_sr_exp: jax.Array,
) -> tuple[
    applications.geic_params, jax.Array, jax.Array, jax.Array, jax.Array, jax.Array
]:
    def _inner_loop(
        p: applications.geic_params,
        x_k: tuple[jax.Array, jax.Array, jax.Array, jax.Array],
    ) -> tuple[
        applications.geic_params,
        tuple[jax.Array, jax.Array, jax.Array, jax.Array, jax.Array],
    ]:
        p_new, e_d_k, e_n_k, e_e_k = applications.step_geic(p, *x_k)

        w_sc_est = p_new.p_w.p_1.W[..., :, : -p.w_sr.shape[-1]]
        diff_w_sc = w_sc_exp - w_sc_est
        nmse_sc_k = jnp.sum(jnp.conj(diff_w_sc) * diff_w_sc) / norm_2_sc

        w_sr_est = p_new.p_w.p_1.W[..., :, -p.w_sr.shape[-1] :]
        diff_w_sr = w_sr_exp - w_sr_est
        nmse_sr_k = jnp.sum(jnp.conj(diff_w_sr) * diff_w_sr) / norm_2_sr
        return p_new, (e_d_k, e_n_k, e_e_k, nmse_sc_k, nmse_sr_k)

    norm_2_sc = jnp.sum(jnp.conj(w_sc_exp) * w_sc_exp)
    norm_2_sr = jnp.sum(jnp.conj(w_sr_exp) * w_sr_exp)

    p_final, errs = jax.lax.scan(_inner_loop, init=p, xs=(m_d, m_n, m_e, e))
    return p_final, *errs


def main():
    ## Setup
    p = signal_generation.parameters.load_from_yaml(PATH_TO_CONFIG)
    m_d, m_n, m_e, e, h_e = signal_generation.generate_signals(p)

    ## Complete setup with state struct & expected filters
    # quiescent beamformer
    w_sr = jnp.ones((m_d.shape[1], 1))
    w_sr = w_sr / (jnp.conj(w_sr.swapaxes(-2, -1)) @ w_sr)

    # L_h_e + L_h_n - 1 to avoid undermodelling for convolutive mixtures in
    # sidelobe cancellation path: multiple lags could be used for the sidelobe
    # cancellation but all those should first be echo cancelled.
    L_h_e = h_e.shape[0]
    p_int = applications.geic_params.construct_params(
        w_sr,
        e.shape[1],
        p.L_sc,
        L_h_e + p.L_sc - 1,
        p.RLS_impl,
        p.lmbd,
        n_levels=0,
    )
    p_casc = applications.geic_params.construct_params(
        w_sr,
        e.shape[1],
        p.L_sc,
        L_h_e + p.L_sc - 1,
        p.RLS_impl,
        p.lmbd,
        n_levels=1,
    )

    # Expected filters
    w_sc_exp_ind = h_e @ jnp.conj(p_int.B)
    w_sc_exp = np.zeros(
        (w_sc_exp_ind.shape[0] + p.L_sc - 1, p_int.B.shape[-1] * p.L_sc)
    )
    for i in range(p.L_sc):
        w_sc_exp[
            i : i + w_sc_exp_ind.shape[0],
            i * p_int.B.shape[-1] : (i + 1) * p_int.B.shape[-1],
        ] = w_sc_exp_ind

    w_sr_exp = jnp.zeros((w_sc_exp.shape[0], w_sr.shape[1]))
    w_sr_exp = w_sr_exp.at[: h_e.shape[0], :].set(h_e @ jnp.conj(w_sr))

    ## Actual simulation loop
    m_d, m_n, m_e, e = (x[..., None] for x in [m_d, m_n, m_e, e])

    _, e_d_int, e_n_int, e_e_int = run_integrated_geic(p_int, m_d, m_n, m_e, e)
    p_casc, e_d_casc, e_n_casc, e_e_casc, nmse_sc, nmse_sr = run_cascaded_geic(
        p_casc, m_d, m_n, m_e, e, w_sc_exp, w_sr_exp
    )

    e_d_int, e_n_int, e_e_int, e_d_casc, e_n_casc, e_e_casc = (
        x[..., 0] for x in [e_d_int, e_n_int, e_e_int, e_d_casc, e_n_casc, e_e_casc]
    )

    ## Plot results
    fig, ax = plt.subplots(constrained_layout=True)
    fig.set_size_inches(8.5, 5.5)
    ax.plot(np.squeeze(m_d)[:, 0], label="Desired signal")
    ax.plot(np.squeeze(m_n)[:, 0], label="Noise")
    ax.plot(np.squeeze(m_e)[:, 0], label="Echo signal")
    ax.set(
        xlabel="time index $n$", ylabel="microphone 0 input", title="Microphone input"
    )
    ax.legend()
    ax.grid()
    ax.autoscale(tight=True, axis="x")

    fig, ax = plt.subplots(constrained_layout=True)
    fig.set_size_inches(8.5, 5.5)
    ax.plot(np.squeeze(e_d_int), label="Desired signal")
    ax.plot(np.squeeze(e_n_int), label="Noise")
    ax.plot(np.squeeze(e_e_int), label="Echo signal")
    ax.set(
        xlabel="time index $n$",
        ylabel="geic output",
        title="Evolution of geic output over time",
    )
    ax.legend()
    ax.grid(True)
    ax.autoscale(tight=True, axis="x")

    fig, ax = plt.subplots(constrained_layout=True)
    fig.set_size_inches(8.5, 5.5)
    ax.semilogy(np.squeeze(np.abs(e_d_int - e_d_casc)), label="Desired signal")
    ax.semilogy(np.squeeze(np.abs(e_n_int - e_n_casc)), label="Noise contribution")
    ax.semilogy(np.squeeze(np.abs(e_e_int - e_e_casc)), label="Echo contribution")
    ax.legend()
    ax.set(
        xlabel="Time index",
        ylabel="Magnitude of difference",
        title="Evolution of difference between integrated and cascade output over time",
    )
    ax.grid(True)
    ax.autoscale(tight=True, axis="x")

    fig, ax = plt.subplots(constrained_layout=True)
    fig.set_size_inches(8.5, 5.5)
    ax.plot(10 * np.log10(nmse_sr), label="Signal reference")
    ax.plot(10 * np.log10(nmse_sc), label="Noise reference")
    ax.set(xlabel="Time index", ylabel="MIS [dB]", title="Evolution of NMSE over time")
    ax.legend()
    ax.grid(True)
    ax.autoscale(tight=True, axis="x")

    fig, ax = plt.subplots(constrained_layout=True)
    fig.set_size_inches(8.5, 5.5)
    ax.plot(w_sc_exp, label="Groundtruth")
    ax.plot(p_casc.p_w.p_1.W[..., :, : -w_sr.shape[-1]], label="Final filter estimate")
    ax.plot(w_sc_exp - p_casc.p_w.p_1.W[..., :, : -w_sr.shape[-1]], label="Difference")
    ax.set(
        xlabel="filter tap",
        ylabel="tap value",
        title="Sidelobe cancellation echo canceller",
    )
    ax.legend()
    ax.grid(True)
    ax.autoscale(tight=True, axis="x")

    fig, ax = plt.subplots(constrained_layout=True)
    fig.set_size_inches(8.5, 5.5)
    ax.plot(w_sr_exp, label="Groundtruth")
    ax.plot(
        p_casc.p_w.p_1.W[..., : w_sr_exp.shape[0], -w_sr.shape[-1] :],
        label="Final filter estimate",
    )
    ax.plot(
        w_sr_exp - p_casc.p_w.p_1.W[..., : w_sr_exp.shape[0], -w_sr.shape[-1] :],
        label="Difference",
    )
    ax.set(
        xlabel="filter tap", ylabel="tap value", title="Signal reference echo canceller"
    )
    ax.legend()
    ax.grid(True)
    ax.autoscale(tight=True, axis="x")

    plt.show(block=True)


if __name__ == "__main__":
    PATH_TO_CONFIG = os.path.join("config", "config.yml")

    jax.config.update("jax_enable_x64", True)

    mpl.use("TkAgg")  # avoid issues when plotting
    plt.ion()

    sys.exit(main())
